# Generated by Django 5.2.4 on 2025-07-30 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorySearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "HistorySearch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive_count", models.IntegerField()),
                ("negative_count", models.IntegerField()),
                ("neutral_count", models.IntegerField()),
                ("cate_count", models.JSONField()),
                ("tag_image", models.TextField()),
                ("top_word", models.JSONField()),
                ("trend_labels", models.JSONField()),
                ("trend_values", models.JSONField()),
                ("report", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_result",
                        to="analyzer.historysearch",
                    ),
                ),
            ],
            options={
                "db_table": "AnalysisResult",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(db_index=True, default="新聞", max_length=20),
                ),
                ("source", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("publish_date", models.DateTimeField()),
                ("summary", models.TextField()),
                ("tags", models.JSONField()),
                ("url", models.URLField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("sentiment", models.CharField(max_length=2)),
                ("sentiment_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "searches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_news",
                        to="analyzer.historysearch",
                    ),
                ),
            ],
            options={
                "db_table": "News",
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(db_index=True, max_length=20)),
                ("source", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("publish_date", models.DateTimeField()),
                ("summary", models.TextField()),
                ("comments", models.JSONField()),
                ("url", models.URLField(unique=True)),
                ("sentiment", models.CharField(max_length=2)),
                ("sentiment_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "searches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_posts",
                        to="analyzer.historysearch",
                    ),
                ),
            ],
            options={
                "db_table": "Posts",
            },
        ),
    ]
