# Generated by Django 5.2.4 on 2025-07-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="search",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analyzer.historysearch",
                verbose_name="相關搜尋",
            ),
        ),
    ]
