# Generated by Django 5.2.4 on 2025-07-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0002_alter_analysisresult_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="keyword",
            field=models.CharField(db_index=True, default="default", max_length=20),
        ),
    ]
