# Generated by Django 5.2.4 on 2025-07-30 18:57

from django.db import migrations
from django.contrib.auth import get_user_model
from django.utils import timezone


def create_anonymous_user(apps, schema_editor):
    User = get_user_model()
    try:
        User.objects.get(username='_anonymous_search_user')
    except User.DoesNotExist:
        User.objects.create_user(username='_anonymous_search_user', 
                                 password='very_secure_random_password_that_doesnt_matter', 
                                 is_active=False,
                                 last_login=timezone.now(),
                                 )

def reverse_anonymous_user(apps, schema_editor):
    User = get_user_model()
    try:
        user = User.objects.get(username='_anonymous_search_user')
        user.delete()
    except User.DoesNotExist:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0003_analysisresult_keyword"),
    ]

    operations = [
        migrations.RunPython(create_anonymous_user, reverse_anonymous_user),
    ]