# Generated by Django 5.2.4 on 2025-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_auto_20250731_0257"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="neg_count",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="neu_count",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="pos_count",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="post_image",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="post_report",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="post_top_word",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="post_trend_labels",
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="post_trend_values",
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="sour_count",
            field=models.JSONField(default={}),
        ),
    ]
