# Generated by Django 5.2.4 on 2025-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_analysisresult_neg_count_analysisresult_neu_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="post_top_word",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="post_trend_labels",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="post_trend_values",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="sour_count",
            field=models.JSONField(default=dict),
        ),
    ]
